config/routes.rb
Pulse::Application.routes.draw do
  match "admins/index" => "admins#index", :as => "admins"
  match "admins/save_settings" => "admins#save_settings", :as => "save_settings"
  match "admins/save_permissions" => "admins#save_permissions", :as => "save_permissions"

  match "/nps" => "nps#summary", :as => "nps_summary"
  match "/nps/detail" => "nps#detail", :as => "nps_detail"

  # This is a workaround.
  # Originally, /auth/google was to be the url for OmniAuth to use.
  # Howevever, a bug made it so that /auth/google would only work the 1st time.
  # After the 1st time, it defaulted to /auth/google_apps.
  # http://github.com/intridea/omniauth/issues#issue/61.
  # Update: this issue has since been fixed. New version should allow us to delete this workaround.
  get '/auth/google', :to => redirect('/auth/google_apps')
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :successful_authentication
  get 'google_login', :to => redirect('/auth/google')
  get 'logout' => 'sessions#destroy'
  match 'user/set_password/:id' => 'users#set_password', :as => 'set_password'
  match 'user/login' => 'sessions#new', :as => 'log_in'

  resources :charts

  match '/chart_javascripts/:action' => 'chart_javascripts', :as => 'chart_javascripts'
  match '/chart/default_size' => 'charts#default_size', :as => 'default_size'
  match '/results/chart_javascripts/:action' => 'chart_javascripts'

  get '/results/rev_by_div' => 'results#rev_by_div', :as => 'rev_by_div_result'
  get '/results/rev_by_prod' => 'results#rev_by_prod', :as => 'rev_by_prod_result'
  get '/results/rev_by_prod/:product' => 'results#single_product', :as => 'single_product_result'
  get '/results/balance_sheet' => 'results#balance_sheet', :as => 'balance_sheet_result'
  get '/results' => 'results#rev_by_div'

  resources :results

  resources :account_details do
    collection do
      get 'decreased'
      get 'increased'
      get 'new_accounts'
      get 'summaries'
    end
  end

  resources :groups

  resources :users

  root :to => "results#rev_by_div"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups, :dependent => :destroy
  has_many :users, :through => :user_groups

  has_many :chart_groups, :dependent => :destroy
  has_many :charts, :through => :chart_groups

  has_many :group_tabs, :dependent => :destroy
  has_many :tabs, :through => :group_tabs
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  #before_filter :check_permission
  before_filter :require_admin

  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end

  #def check_permission
  #  #render_layout_only "You don't have permission to view this page" unless current_user.can_see_this_tab?('Administrator')
  #  render_layout_only unless current_user.can_see_this_tab?('Administrator')
  #end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
-if @group.errors.any?
  #error_explanation
    %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
    %ul
      - @group.errors.full_messages.each do |msg|
        %li= msg
.group
  = f.label :name, "Name", :class => :label
  = f.text_field :name, :class => 'text_field'

.group.navform.wat-cf
  %button.button{:type => 'submit'}
    = image_tag("web-app-theme/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  = link_to raw("#{image_tag("web-app-theme/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}")} #{t("web-app-theme.cancel", :default => "Cancel")}"), groups_path, :class => "button"

= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

app/views/groups/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), groups_path
      %li= link_to t("web-app-theme.new", :default => "New"), new_group_path
      %li.active= link_to t("web-app-theme.edit", :default => "Edit"), edit_group_path
  .content
    %h2.title Editing group
    .inner
      - form_for @group, :url => group_path(@group), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/groups/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", groups_path
      %li= link_to "New", new_group_path
  .content
    %h2.title Listing groups
    .inner
      %table.table
        %tr
          %th.first Name
          %th.last &nbsp;
        - @groups.each do |group|
          %tr{:class => cycle("odd", "even")}
            %td= group.name
            %td.last
              = link_to "Show", group
              |
              = link_to "Edit", edit_group_path(group)
              |
              = link_to "Destroy", group, :confirm => "Are you sure?", :method => :delete
      .actions-bar.wat-cf
        .actions

app/views/groups/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), groups_path
      %li.active= link_to t("web-app-theme.new", :default => "New"), new_group_path
  .content
    %h2.title New group
    .inner
      - form_for @group, :url => groups_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/groups/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", groups_path
      %li= link_to "New", new_group_path
      %li.active= link_to "Show", group_path
  .content
    .inner
      %p
        %b Name:
        = @group.name

      %br/
      .wat-cf
        #{ link_to raw("#{image_tag("web-app-theme/application_edit.png", :alt => t("web-app-theme.edit", :default=> "Edit"))} #{t("web-app-theme.edit", :default=> "Edit")}"), edit_group_path(@group), :class => "button" } 
        #{ link_to raw("#{image_tag("web-app-theme/cross.png", :alt => t("web-app-theme.delete", :default=> "Delete"))} #{t("web-app-theme.delete", :default => "Delete")}"), group_path(@group), :method => "delete", :class => "button", :confirm => t("web-app-theme.confirm", :default => "Are you sure?") }