config/routes.rb
Pulse::Application.routes.draw do
  match "admins/index" => "admins#index", :as => "admins"
  match "admins/save_settings" => "admins#save_settings", :as => "save_settings"
  match "admins/save_permissions" => "admins#save_permissions", :as => "save_permissions"

  match "/nps" => "nps#summary", :as => "nps_summary"
  match "/nps/detail" => "nps#detail", :as => "nps_detail"

  # This is a workaround.
  # Originally, /auth/google was to be the url for OmniAuth to use.
  # Howevever, a bug made it so that /auth/google would only work the 1st time.
  # After the 1st time, it defaulted to /auth/google_apps.
  # http://github.com/intridea/omniauth/issues#issue/61.
  # Update: this issue has since been fixed. New version should allow us to delete this workaround.
  get '/auth/google', :to => redirect('/auth/google_apps')
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :successful_authentication
  get 'google_login', :to => redirect('/auth/google')
  get 'logout' => 'sessions#destroy'
  match 'user/set_password/:id' => 'users#set_password', :as => 'set_password'
  match 'user/login' => 'sessions#new', :as => 'log_in'

  resources :charts

  match '/chart_javascripts/:action' => 'chart_javascripts', :as => 'chart_javascripts'
  match '/chart/default_size' => 'charts#default_size', :as => 'default_size'
  match '/results/chart_javascripts/:action' => 'chart_javascripts'

  get '/results/rev_by_div' => 'results#rev_by_div', :as => 'rev_by_div_result'
  get '/results/rev_by_prod' => 'results#rev_by_prod', :as => 'rev_by_prod_result'
  get '/results/rev_by_prod/:product' => 'results#single_product', :as => 'single_product_result'
  get '/results/balance_sheet' => 'results#balance_sheet', :as => 'balance_sheet_result'
  get '/results' => 'results#rev_by_div'

  resources :results

  resources :account_details do
    collection do
      get 'decreased'
      get 'increased'
      get 'new_accounts'
      get 'summaries'
    end
  end

  resources :groups

  resources :users

  root :to => "results#rev_by_div"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, :dependent => :destroy
  has_many :user_groups, :dependent => :destroy
  has_many :groups, :through => :user_groups

  validates_presence_of :email
  validates_inclusion_of :allowed_to_login, :in => [true, false]

  def self.find_authorized_by_id_or_email!(id_or_email)
    if id_or_email.is_a?(Integer) || (id_or_email && id_or_email.match(/^[0-9]+$/))
      user = find_by_id(id_or_email)
    else
      user = find_by_email(id_or_email)
    end
    raise NotFound.new(id_or_email) unless user
    raise Locked unless user.allowed_to_login
    user
  end

  def charts
    groups.map(&:charts).flatten
  end

  class NotFound < StandardError
    attr_reader :identifier
    def initialize(identifier)
      super "User '#{identifier}' not found. Create before they authenticate"
    end
  end

  class Locked < StandardError; end

  def can_see_this_tab?(tab_name)
    groups = self.groups
    can_see = false
    groups.each do |group|
      if group.tabs.map(&:name).include? tab_name  
        can_see = true
        break
      end
    end
    can_see
  end

  def self.make_local_admin
    user = User.find_or_create_by_email('ndgiang84@xiga.info')
    user.update_attributes(:allowed_to_login => true, :is_admin => true)
    Group.all.each { |g| user.groups << g }
    User.set_password(user.id, '123456')
  end

  def self.authenticate(email, password)
    user = User.find_by_email(email)

    if user
      salt = user.salt || ""
      expected_password = encrypted_password(password, salt)
      user = nil unless user.hashed_password == expected_password
    end

    user
  end

  def self.set_password(user_id, new_password)
    user = User.find_by_id(user_id)
    user.password = new_password
    user.hashed_password = encrypted_password(new_password, user.salt)
    user.save
  end

  def password
    @password
  end
            
  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end

  private

  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
              
  def self.encrypted_password(password,salt)
    string_to_hash = password + "pulse" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin#, :check_permission

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    @user.groups = [] if params[:user][:group_ids].blank?

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def set_password
    if request.post?
      User.set_password(params[:id], params[:password])
      redirect_to users_path, :notice => 'User was successfully set password.'
    else
      @user = User.find_by_id(params[:id])
    end
  end

  #def check_permission
  #  #render_layout_only "You don't have permission to view this page" unless current_user.can_see_this_tab?('Administrator')
  #  render_layout_only unless current_user.can_see_this_tab?('Administrator')
  #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-if @user.errors.any?
  #error_explanation
    %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
.group
  = f.label :email, "Email", :class => :label
  = f.text_field :email, :class => 'text_field'

.group
  = f.check_box :allowed_to_login, :class => 'check_box_field'
  = f.label :allowed_to_login, "Allowed to login", :class => :label, :style => "display:inline"

.group
  = f.check_box :is_admin, :class => 'check_box_field'
  = f.label :is_admin, "Is admin", :class => :label, :style => "display:inline"

.group
  - Group.all.each do |group|
    = check_box_tag 'user[group_ids][]', group.id, @user.groups.include?(group), :id => "user_group_#{group.id}"
    = label_tag "user_group_#{group.id}", group.name
    %br/
        
.group.navform.wat-cf
  %button.button{:type => 'submit'}
    = image_tag("web-app-theme/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  = link_to raw("#{image_tag("web-app-theme/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}")} #{t("web-app-theme.cancel", :default => "Cancel")}"), users_path, :class => "button"

app/views/users/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), users_path
      %li= link_to t("web-app-theme.new", :default => "New"), new_user_path
      %li.active= link_to t("web-app-theme.edit", :default => "Edit"), edit_user_path
  .content
    %h2.title Editing user
    .inner
      - form_for @user, :url => user_path(@user), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/users/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", users_path
      %li= link_to "New", new_user_path
  .content
    %h2.title Listing users
    .inner
      %table.table
        %tr
          %th.first Email
          %th Password
          %th Allowed to login
          %th Groups
          %th.last{:colspan => "2"} &nbsp;
        - @users.each do |user|
          %tr{:class => cycle("odd", "even")}
            %td= mail_to user.email
            %td
              - if user.hashed_password == nil
                N/A
              - else
                not shown
            %td= user.allowed_to_login
            %td= user.groups.map(&:name).join(', ')
            %td.last{:colspan => "2"}
              = link_to "Set password", set_password_path(user)
              |
              = link_to "Show", user
              |
              = link_to "Edit", edit_user_path(user)
              |
              = link_to "Destroy", user, :confirm => "Are you sure?", :method => :delete
      .actions-bar.wat-cf
        .actions

app/views/users/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), users_path
      %li.active= link_to t("web-app-theme.new", :default => "New"), new_user_path
  .content
    %h2.title New user
    .inner
      - form_for @user, :url => users_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/users/set_password.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), users_path
      %li.active= link_to t("web-app-theme.new", :default => "Set password"), new_user_path
  .content
    %h2.title Set password
    .inner
      - form_for :user, :url => set_password_path, :html => { :class => :form } do |f|
        .group
          = f.label :email, "Email: ", :class => :label, :style => "display:inline"
          = @user.email

        .group
          = label :password, "Password: ", :class => :label, :style => "display:inline"
          = password_field_tag :password
          
        .group.navform.wat-cf
          %button.button{:type => 'submit'}
            = image_tag("web-app-theme/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
            = t("web-app-theme.save", :default => "Save")
          = link_to raw("#{image_tag("web-app-theme/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}")} #{t("web-app-theme.cancel", :default => "Cancel")}"), users_path, :class => "button"

app/views/users/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", users_path
      %li= link_to "New", new_user_path
      %li.active= link_to "Show", user_path
  .content
    .inner
      %p
        %b Email:
        = @user.email
      %p
        %b Allowed to login:
        = @user.allowed_to_login
      %p
        %b Is admin:
        = @user.is_admin
      %p
        %b Groups:
        = @user.groups.map(&:name).join(', ')

      %br/
      .wat-cf
        #{ link_to raw("#{image_tag("web-app-theme/application_edit.png", :alt => t("web-app-theme.edit", :default=> "Edit"))} #{t("web-app-theme.edit", :default=> "Edit")}"), edit_user_path(@user), :class => "button" } 
        #{ link_to raw("#{image_tag("web-app-theme/cross.png", :alt => t("web-app-theme.delete", :default=> "Delete"))} #{t("web-app-theme.delete", :default => "Delete")}"), user_path(@user), :method => "delete", :class => "button", :confirm => t("web-app-theme.confirm", :default => "Are you sure?") }