config/routes.rb
Pulse::Application.routes.draw do
  match "admins/index" => "admins#index", :as => "admins"
  match "admins/save_settings" => "admins#save_settings", :as => "save_settings"
  match "admins/save_permissions" => "admins#save_permissions", :as => "save_permissions"

  match "/nps" => "nps#summary", :as => "nps_summary"
  match "/nps/detail" => "nps#detail", :as => "nps_detail"

  # This is a workaround.
  # Originally, /auth/google was to be the url for OmniAuth to use.
  # Howevever, a bug made it so that /auth/google would only work the 1st time.
  # After the 1st time, it defaulted to /auth/google_apps.
  # http://github.com/intridea/omniauth/issues#issue/61.
  # Update: this issue has since been fixed. New version should allow us to delete this workaround.
  get '/auth/google', :to => redirect('/auth/google_apps')
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :successful_authentication
  get 'google_login', :to => redirect('/auth/google')
  get 'logout' => 'sessions#destroy'
  match 'user/set_password/:id' => 'users#set_password', :as => 'set_password'
  match 'user/login' => 'sessions#new', :as => 'log_in'

  resources :charts

  match '/chart_javascripts/:action' => 'chart_javascripts', :as => 'chart_javascripts'
  match '/chart/default_size' => 'charts#default_size', :as => 'default_size'
  match '/results/chart_javascripts/:action' => 'chart_javascripts'

  get '/results/rev_by_div' => 'results#rev_by_div', :as => 'rev_by_div_result'
  get '/results/rev_by_prod' => 'results#rev_by_prod', :as => 'rev_by_prod_result'
  get '/results/rev_by_prod/:product' => 'results#single_product', :as => 'single_product_result'
  get '/results/balance_sheet' => 'results#balance_sheet', :as => 'balance_sheet_result'
  get '/results' => 'results#rev_by_div'

  resources :results

  resources :account_details do
    collection do
      get 'decreased'
      get 'increased'
      get 'new_accounts'
      get 'summaries'
    end
  end

  resources :groups

  resources :users

  root :to => "results#rev_by_div"
end

app/models/result.rb
require 'active_support/ordered_hash'

class Result < ActiveRecord::Base

  scope :types, proc { |args| where(:Type => args) }
  scope :terms, proc { |args| where(:Term => args) }
  scope :classes, proc { |args| where(:Class => args) }
  scope :items, proc { |args| where(:Item => args) }
  scope :sections, proc { |args| where(:Section => args) }

  # Hashes for some fields.
  # Key is db value, value is displayed version.
  # Some keys look exactly like the values, but this was intentional in case db values change.
  def self.terms_hash
    @terms ||= ordered_hash([
      ['CMTD', 'Month To Date'],
      ['CYQT', 'Quarter to Date'],
      ['CYTD', 'Year to Date'],
    ])
  end

  def self.types_hash
    @types ||= ordered_hash([
      ['Actual', 'Actual'],
      ['Plan', 'Plan'],
      ['Prior Year', 'Prior Year'],
    ])
  end

  def self.classes_hash
    @classes ||= ordered_hash([
      ['Domestic', 'Domestic'],
      ['International', 'International'],
      ['Air', 'Air'],
      ['Motorcycle', 'Motorcycle'],
    ])
  end

  # This should probably go in lib/ as ActiveSupport::OrderedHash.initialize().
  def self.ordered_hash(elements)
    o_hash = ActiveSupport::OrderedHash.new
    elements.each do |db_name, display_name|
      o_hash[db_name] = display_name
    end
    o_hash
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :check_permission

  def table
    @results = Result.sections('Sales').items('EQUAL')
    @terms = @results.terms_hash.delete_if { |key, val| !['CMTD', 'CYTD'].include?(key) }
    @classes = @results.classes_hash
    @types = @results.types_hash
  end

  def rev_by_div
    charts_by_div = %w(domestic_current_month
                       domestic_current_quarter
                       domestic_current_year
                       international_current_month
                       international_current_quarter
                       international_current_year
                       wrrs_current_month
                       wrrs_current_quarter
                       wrrs_current_year)
    @charts = Chart.all(:conditions => ["name in (?)", charts_by_div]).delete_if { |c| !current_user.charts.map(&:name).include? c.name }
  end

  def rev_by_prod
    total_products = Result.select('item').map { |i| i.attributes.values }.flatten.compact.uniq.count
    @total_charts = total_products * 3
    @charts = [Chart.find_by_name('product')].delete_if { |c| !current_user.charts.map(&:name).include? c.name }
    @items = Result.sections('Sales').select('item').map { |i| i.attributes.values }.flatten.compact.uniq
  end

  def balance_sheet
    @charts = [Chart.find_by_name('line_of_credit')].delete_if { |c| !current_user.charts.map(&:name).include? c.name }
  end

  def check_permission
    #render_layout_only "You don't have permission to view this page" unless current_user.can_see_this_tab?('Results')
    render_layout_only unless current_user.can_see_this_tab?('Results')
  end

  def single_product
    @product = params[:product]
    @total_charts = 3
    @charts = [Chart.find_by_name('single_product')].delete_if { |c| !current_user.charts.map(&:name).include? c.name }
    @items = Result.sections('Sales').select('item').map { |i| i.attributes.values }.flatten.compact.uniq
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def chart_placeholder(name, total=nil)
    charts << name

    if total
      chart_divs = ""
      for index in (0...total)
        chart_divs << content_tag(:div, nil, :id => "#{name}-#{index}", :style => "float:left; padding: 10px; box-shadow: 0 0 5px #BBBBBB; margin: 10px;")
      end
      chart_divs.html_safe
    else
      content_tag :div, nil, :id => name
    end
  end

  # instance variable to be used in application layout which will tell HighCharts which charts to render.
  def charts
    @chart_names ||= []
  end
end

app/views/results/balance_sheet.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Rev by Division", rev_by_div_result_path
      %li= link_to "Rev by Product", rev_by_prod_result_path
      %li.last.active= link_to "Balance Sheet", balance_sheet_result_path
  .content
    #charts-balance-sheet
      - @charts.each do |chart|
        = chart_placeholder chart.name

app/views/results/rev_by_div.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "Rev by Division", rev_by_div_result_path
      %li= link_to "Rev by Product", rev_by_prod_result_path
      %li.last= link_to "Balance Sheet", balance_sheet_result_path
  .content
    - @charts.each do |chart|
      = chart_placeholder chart.name

app/views/results/rev_by_prod.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Rev by Division", rev_by_div_result_path
      %li.active= link_to "Rev by Product", rev_by_prod_result_path
      %li.last= link_to "Balance Sheet", balance_sheet_result_path
  .content
    .options
      Display: 
      = select_tag 'product-chart', options_for_select([['All products', 'all']] + @items.map { |i| [i, i] })
    #charts-area
      - @charts.each do |chart|
        = chart_placeholder chart.name, @total_charts

app/views/results/single_product.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "Rev by Division", rev_by_div_result_path
      %li.active= link_to "Rev by Product", rev_by_prod_result_path
      %li.last= link_to "Balance Sheet", balance_sheet_result_path
  .content
    .options
      Display: 
      = select_tag 'product-chart', options_for_select([['All products', 'all']] + @items.map { |i| [i, i] }, @product)
    #charts-area
      - @charts.each do |chart|
        = chart_placeholder chart.name, @total_charts