config/routes.rb
Pulse::Application.routes.draw do
  match "admins/index" => "admins#index", :as => "admins"
  match "admins/save_settings" => "admins#save_settings", :as => "save_settings"
  match "admins/save_permissions" => "admins#save_permissions", :as => "save_permissions"

  match "/nps" => "nps#summary", :as => "nps_summary"
  match "/nps/detail" => "nps#detail", :as => "nps_detail"

  # This is a workaround.
  # Originally, /auth/google was to be the url for OmniAuth to use.
  # Howevever, a bug made it so that /auth/google would only work the 1st time.
  # After the 1st time, it defaulted to /auth/google_apps.
  # http://github.com/intridea/omniauth/issues#issue/61.
  # Update: this issue has since been fixed. New version should allow us to delete this workaround.
  get '/auth/google', :to => redirect('/auth/google_apps')
  match '/auth/:provider/callback', :to => 'sessions#create', :as => :successful_authentication
  get 'google_login', :to => redirect('/auth/google')
  get 'logout' => 'sessions#destroy'
  match 'user/set_password/:id' => 'users#set_password', :as => 'set_password'
  match 'user/login' => 'sessions#new', :as => 'log_in'

  resources :charts

  match '/chart_javascripts/:action' => 'chart_javascripts', :as => 'chart_javascripts'
  match '/chart/default_size' => 'charts#default_size', :as => 'default_size'
  match '/results/chart_javascripts/:action' => 'chart_javascripts'

  get '/results/rev_by_div' => 'results#rev_by_div', :as => 'rev_by_div_result'
  get '/results/rev_by_prod' => 'results#rev_by_prod', :as => 'rev_by_prod_result'
  get '/results/rev_by_prod/:product' => 'results#single_product', :as => 'single_product_result'
  get '/results/balance_sheet' => 'results#balance_sheet', :as => 'balance_sheet_result'
  get '/results' => 'results#rev_by_div'

  resources :results

  resources :account_details do
    collection do
      get 'decreased'
      get 'increased'
      get 'new_accounts'
      get 'summaries'
    end
  end

  resources :groups

  resources :users

  root :to => "results#rev_by_div"
end

app/models/chart.rb
# This model only really represents the chart's name.
# This model was created to accommodate groups.

class Chart < ActiveRecord::Base

  has_many :chart_groups, :dependent => :destroy
  has_many :groups, :through => :chart_groups

  def self.names
    chart_names = %w(line_of_credit
                     trend_line
                     domestic_current_month
                     domestic_current_quarter
                     domestic_current_year
                     international_current_month
                     international_current_quarter
                     international_current_year
                     wrrs_current_month
                     wrrs_current_quarter
                     wrrs_current_year
                     product
                     single_product)
    @names ||= chart_names.freeze
  end

  validates_presence_of :name
  validates_inclusion_of :name, :in => names

  DEFAULT_WIDTH = {
    self.names[0] => 370,
    self.names[2] => 500,
    self.names[3] => 500,
    self.names[4] => 500,
    self.names[5] => 500,
    self.names[6] => 500,
    self.names[7] => 500,
    self.names[8] => 500,
    self.names[9] => 500,
    self.names[10] => 500,
    self.names[11] => 430,
    self.names[12] => 430
  }

  DEFAULT_HEIGHT = {
    self.names[0] => 350,
    self.names[2] => 211,
    self.names[3] => 211,
    self.names[4] => 211,
    self.names[5] => 211,
    self.names[6] => 211,
    self.names[7] => 211,
    self.names[8] => 211,
    self.names[9] => 211,
    self.names[10] => 211,
    self.names[11] => 211,
    self.names[12] => 211
  }

  def self.reset_all_size
    Chart.all.each_with_index do |c, i|
      c.update_attributes(:width => Chart::DEFAULT_WIDTH[Chart::names[i]], :height => Chart::DEFAULT_HEIGHT[Chart::names[i]])
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  #before_filter :check_permission
  before_filter :require_admin, :except => [:index, :show]

  def index
    @charts = Chart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @charts }
    end
  end

  # GET /charts/1
  # GET /charts/1.xml
  def show
    @chart = Chart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/new
  # GET /charts/new.xml
  def new
    @chart = Chart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chart }
    end
  end

  # GET /charts/1/edit
  def edit
    @chart = Chart.find(params[:id])
  end

  # POST /charts
  # POST /charts.xml
  def create
    @chart = Chart.new(params[:chart])

    respond_to do |format|
      if @chart.save
        format.html { redirect_to(@chart, :notice => 'Chart was successfully created.') }
        format.xml  { render :xml => @chart, :status => :created, :location => @chart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charts/1
  # PUT /charts/1.xml
  def update
    @chart = Chart.find(params[:id])
    @chart.groups = [] if params[:chart][:group_ids].blank?

    respond_to do |format|
      if @chart.update_attributes(params[:chart])
        format.html { redirect_to(@chart, :notice => 'Chart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.xml
  def destroy
    @chart = Chart.find(params[:id])
    @chart.destroy

    respond_to do |format|
      format.html { redirect_to(charts_url) }
      format.xml  { head :ok }
    end
  end

  def trend_line_chart
  end

  def default_size
    Chart.reset_all_size
    redirect_to charts_path, :notice => "Default size reset."
  end

  #def check_permission
  #  #render_layout_only "You don't have permission to view this page" unless current_user.can_see_this_tab?('Administrator')
  #  render_layout_only unless current_user.can_see_this_tab?('Administrator')
  #end
end

app/views/charts/_form.html.haml
-if @chart.errors.any?
  #error_explanation
    %h2= "#{pluralize(@chart.errors.count, "error")} prohibited this chart from being saved:"
    %ul
      - @chart.errors.full_messages.each do |msg|
        %li= msg
.group
  = check_box_tag :groups_select_all
  = label_tag :groups_select_all, "Select All"
  %br/
  %br/
  #charts_groups
    - Group.all.each do |group|
      = check_box_tag 'chart[group_ids][]', group.id, @chart.groups.include?(group), :id => "chart_group_#{group.id}", :class => 'charts_groups'
      = label_tag "chart_group_#{group.id}", group.name
      %br/

.group
  = f.label :width, :class => "label"
  = f.text_field :width, :'default-width' => Chart::DEFAULT_WIDTH[@chart.name]

.group
  = f.label :height, :class => "label"
  = f.text_field :height, :'default-height' => Chart::DEFAULT_HEIGHT[@chart.name]

- unless @chart.new_record?
  = link_to "Use", "#", :id => 'reset-width-height'
  default width, height

.group.navform.wat-cf
  %button.button{:type => 'submit'}
    = image_tag("web-app-theme/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  = link_to raw("#{image_tag("web-app-theme/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}")} #{t("web-app-theme.cancel", :default => "Cancel")}"), charts_path, :class => "button"

app/views/charts/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), charts_path
      %li.active= link_to t("web-app-theme.edit", :default => "Edit"), edit_chart_path
  .content
    :plain
      Editing #{@chart.name}
    .inner
      - form_for @chart, :url => chart_path(@chart), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/charts/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", charts_path
  .content
    %h2.title Listing charts
    .inner
      %table.table
        %tr
          %th.first Name
          %th Groups
          %th Width
          %th Height
          %th.last &nbsp;
        - @charts.each do |chart|
          %tr{:class => cycle("odd", "even")}
            %td= chart.name
            %td= chart.groups.map(&:name).join(', ')
            %td= chart.width
            %td= chart.height
            %td.last
              = link_to "Edit", edit_chart_path(chart)
      .actions-bar.wat-cf
        .actions
      = link_to "Reset all", default_size_path
      width, height to default (best fit 1024x768)

app/views/charts/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to t("web-app-theme.list", :default => "List"), charts_path
      %li.active= link_to t("web-app-theme.new", :default => "New"), new_chart_path
  .content
    %h2.title New chart
    .inner
      - form_for @chart, :url => charts_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/charts/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", charts_path
      %li.active= link_to "Show", chart_path
  .content
    .inner
      %p
        %b Name:
        = @chart.name
      %p
        %b Groups:
        = @chart.groups.map(&:name).join(', ')
      %p
        %b Width:
        = @chart.width
      %p
        %b Height:
        = @chart.height

      %br/
      .wat-cf
        #{ link_to raw("#{image_tag("web-app-theme/application_edit.png", :alt => t("web-app-theme.edit", :default=> "Edit"))} #{t("web-app-theme.edit", :default=> "Edit")}"), edit_chart_path(@chart), :class => "button" } 
        #{ link_to raw("#{image_tag("web-app-theme/cross.png", :alt => t("web-app-theme.delete", :default=> "Delete"))} #{t("web-app-theme.delete", :default => "Delete")}"), chart_path(@chart), :method => "delete", :class => "button", :confirm => t("web-app-theme.confirm", :default => "Are you sure?") }